### ISSUE TITLE
/simple-upload is not functional since pyDataverse update

### ISSUE THREAD

**Issue by antonpolishko** [CoronaWhy/dataverse-integrations#5]
Since commit 7ef7b18804445a6dedd66f701cc27c3c89e3048d `NativeApi` is not present, thus
```
from pyDataverse.api import Api, NativeApi
```
isn't working

**Comment by skasberger** [comment]
NativeApi is present in the develop branch. Maybe you went back to the last release from master branch. A new release will come in the next weeks.

**Comment by memetics19** [comment]
@antonpolishko  check my pr #4. There's something wrong with persistent id. Need to check.
